### ISSUE TITLE
Fall back to other fields if display name is empty

### ISSUE THREAD

**Issue by rsjtdrjgfuzkfg** [rsjtdrjgfuzkfg/thunderbird-birthdaycalendar#13]
> I propose to first check fields "first name", "family name" and then / or "email" and display it and only in case they are empty, displaying the id.

@1u from https://github.com/rsjtdrjgfuzkfg/thunderbird-birthdaycalendar/issues/8#issuecomment-1013120546

**Comment by 1u** [comment]
Thx for opening the issue

> If such contacts are common I can see the value in having a better fallback. I was under the impression that pretty much the only way you can get there is by actively deleting the display name, or by having a contact that truly has no name.  
> this might be a stupid and tangential question, but how did you get those contacts?

Yes, I asked this myself as well! It is kind of obvious that those contacts are newer than the others. Seems like they are automatically added from the recipients into the address book (with only the email field) while sending emails. I'll keep you updated if I find out more.

**Comment by 1u** [comment]
I checked if the problems are my sync settings or a specific addon.

It seems Thunderbird adds contacts to the address book with all fields empty except email address (if set in settings to add them automatically while sending). Can someone confirm?

Thunderbird 78.14.0

**Comment by rsjtdrjgfuzkfg** [comment]
At least in Thunderbird 91 it populates the display name with whatever name you entered with the email address. It does not, however, populate the field if you enter a raw email address without any name (it will still implicitly generate a display name in some views based on the local part of the email address, though?!).

That all said, I could not find a way to associate a birthday while sending, so these contacts would not show in a birthday calendar. Did you manually add a birthday without also adding a name?

**Comment by 1u** [comment]
Yes, I added a Birthday without adding a name.

Now on TB v.91 as well.

Same here, if I type in to the To: Field
- `Test7 Name <test7@example.com>` additionally adds the names to the address book fields (Name, Family name, Display name)  
- `test6@example.com` just adds the email to the address book

FYI: This issue has absolutely no priority to me. I'm happy now to understand how this happened, that I have an ID ("random numbres") displayed in the birthday calendar. 

In meanwhile I'll try to remember typing a display name when I add a birthday date to the address book :)

thx for your nice and helpful work on the birthdaycalendar!

**Comment by 1u** [comment]
:tada:
