### ISSUE TITLE
Request: Add support for CardDAV

### ISSUE THREAD

**Issue by ThoMagnum** [rsjtdrjgfuzkfg/thunderbird-birthdaycalendar#19]
Hello Dirk,

I would very appreciaet if you can add support for CardDAV addressbooks.
Unfortunately only local adrdressbooks are supportet right now.

Thank you very much in advance.

Best regards, Thomas

**Comment by rsjtdrjgfuzkfg** [comment]
All Thunderbird address books should be supported. I just tested an CardDAV address book and cannot reproduce this issue, thus closing as invalid.

If you experience issues with CardDAV address books, please outline *exactly* what you did, what you expected to happen, and what happened instead.

For example, I could imagine that you are not using a CardDAV address book in Thunderbird, but instead installed an address book replacer like CardBook, and use your CardDAV address book with that. There are multiple closed issues around that topic; mixing CardBook with other address book add-ons won't work. You should stick to CardBook's own features if you want to use it, which also include mechanisms to get birthday events.
