### ISSUE TITLE
Uplift to be compatible with TB 113?

### ISSUE THREAD

**Issue by dbrewood** [rsjtdrjgfuzkfg/thunderbird-birthdaycalendar#20]
Are there any plans to update the extension to be compatible with the forthcoming TB 113 release?

**Comment by rsjtdrjgfuzkfg** [comment]
No, I generally don't support beta versions. "Accidental" beta support might happen at some point in the 115 release preparations, but don't count on it.

(If somebody wants to contribute a patch I would be open to merging it though, feel free to create a PR if you're interested.)
