### ISSUE TITLE
Unexpected property

### ISSUE THREAD

**Issue by dbrewood** [rsjtdrjgfuzkfg/thunderbird-birthdaycalendar#24]
I've noted this error in the error console, and I've been told it should be reported to you?

`[addons.webextension.birthdaycalendar@rsjtdrjgfuzkfg.com](mailto:addons.webextension.birthdaycalendar@rsjtdrjgfuzkfg.com) WARN    Loading extension '[birthdaycalendar@rsjtdrjgfuzkfg.com](mailto:birthdaycalendar@rsjtdrjgfuzkfg.com)': Reading manifest: Warning processing calendar_provider: An unexpected property was found in the WebExtension manifest.`

It means nothing to me, but I'm hoping it does to you? If you need more information, please advise what you require.

**Comment by rsjtdrjgfuzkfg** [comment]
Not sure who told you that, but this message is necessary for the add-on to function as intended.
There is no reason to worry or take any action.

**Comment by dbrewood** [comment]
Okay, thank you for responding and clarifying....

**Comment by Betterbird** [comment]
We gave that advice. `An **unexpected** property was found in the WebExtension manifest.` seems like an error, well, at least it's classified as "WARN". Those errors are flooding the error console and make it difficult to spot real issues:
![image](https://github.com/rsjtdrjgfuzkfg/thunderbird-birthdaycalendar/assets/86832723/e8f2dccc-c38a-40af-8df7-33e75b82c057)


Do you know the background? What is causing the warning? Can that be avoided? We don't think the warning is useful, so we can either file a bug at Mozilla to tone it down or tone it down in Betterbird.

**Comment by Betterbird** [comment]
Thanks for the comment. In our fork we're in the lucky position to be able to change anything without asking permission. We'll investigate. As we said, littering the console with useless information is not correct in our opinion. Mozilla is likely not to accept a patch only affecting WE Experiments since they are not supported in FF.

**Comment by Betterbird** [comment]
We looked at this a bit more, before we didn't see the forest for the trees.

So the warning is about this:
```
  "calendar_provider": {
    "capabilities": {
      "timezones": {
        "floating": true,
        "UTC": false
      },
      "attachments": false,
      "priority": false,
      "privacy": false,
      "alarms": {
        "count": 0
      },
      "tasks": false,
      "events": true,
      "requires_network": true,
      "mutable": false
    }
  },
```
in the manifest. So there is an "upstream" experiment which does the same? Where/which? Why is added "illegal" properties to the manifest a good idea?
