### ISSUE TITLE
Warning processing calendar_provider .... WebExtension manifest

### ISSUE THREAD

**Issue by dbrewood** [rsjtdrjgfuzkfg/thunderbird-birthdaycalendar#25]
I'm seeing the following error in the console:

`addons.webextension.birthdaycalendar@rsjtdrjgfuzkfg.com	WARN	Loading extension 'birthdaycalendar@rsjtdrjgfuzkfg.com': Reading manifest: Warning processing calendar_provider: An unexpected property was found in the WebExtension manifest.`

This is when getting contact data from the 'iCloud Contacts' on my Mac.

Any ideas?

**Comment by rsjtdrjgfuzkfg** [comment]
Duplicate of #24, please search existing issues before opening a new one. Thanks!
