### ISSUE TITLE
X-APPLE-OMIT-YEAR causing issues

### ISSUE THREAD

**Issue by ElTh0r0** [rsjtdrjgfuzkfg/thunderbird-birthdaycalendar#29]
Hi,
I noticed, that birthdays of some of my contacts had been missing in the calendar. After some debugging I found the root cause in X-APPLE-OMIT-YEAR added to contacts without a year. (assuming #28 could be related to that)

Example:
```
BEGIN:VCARD
VERSION:3.0
BDAY;X-APPLE-OMIT-YEAR=1604;VALUE=DATE:16040105
FN:NoYear\, Birthd
REV:20240227T183915Z
N:NoYear;Birthd
UID:7e3cb6f6-c370-4d9c-bb6e-8b6180109596
PRODID:-//Open-Xchange//7.10.6-Rev59//EN
END:VCARD
```

X-APPLE-OMIT-YEAR seems to be a non-standard extension, but is used by several applications. Would you consider "supporting" it (by just ignoring/skipping it)?
<sub>Once I properly understand regex, I might be able to create a patch at some time, but you might be quicker ^^</sub>

**Comment by rsjtdrjgfuzkfg** [comment]
Should be fixed by 08475cb7fdbf7111227dce9c2a737fc37167f9bd
