### ISSUE TITLE
Not compatible with TB 125.0

### ISSUE THREAD

**Issue by Horst12** [rsjtdrjgfuzkfg/thunderbird-birthdaycalendar#31]
I had to patch the XPI to make it running under TB 125.0
No problem so far, it still runs fine

**Comment by rsjtdrjgfuzkfg** [comment]
The compatibility information indicates the versions that the add-on is officially supported on, I only update it when a new supported version of Thunderbird releases. As I don't support beta versions, the next time that will happen is Thunderbird 128.

As educated user, you are of course more than welcome to use beta versions and do the bump yourself and/or disable compatibility checks :)

**Comment by Horst12** [comment]
TB 125.0 is not a beta version !

**Comment by rsjtdrjgfuzkfg** [comment]
125.0 is a test build that is [not intended to be used by anyone](https://thunderbird.topicbox.com/groups/planning/Tf458e19e4446e1c6) and not a beta version; I thus assumed you're on beta, as that made much more sense to me.

To be clear: I only support official release versions (no beta, no nightly, no candidates, no test builds, etc.).

I might change that policy to only official esr versions once Thunderbird changes to monthly releases, given that I don't have the resources to properly support monthly releases that can include major internal changes - but let's see what the future brings first.

**Comment by MattGapp** [comment]
> I had to patch the XPI to make it running under TB 125.0 No problem so far, it still runs fine

Please can you provide me the patch?

**Comment by Horst12** [comment]
Download and open the **birthdaycalendar.xpi** (its just a zip file).
Edit the file manifest.json
Change the beginning as show below, repack it and install the modified version in Thunderbird.

{
  "manifest_version": 2,
  "applications": {
    "gecko": {
      "id": "birthdaycalendar@rsjtdrjgfuzkfg.com",
      "strict_min_version": "102.0",
      **"strict_max_version": "125.*"**
    }
  },
