### ISSUE TITLE
Not compatible with TB 129

### ISSUE THREAD

**Issue by Ollipop030** [rsjtdrjgfuzkfg/thunderbird-birthdaycalendar#33]
![grafik](https://github.com/user-attachments/assets/640fe204-e745-4d67-9920-9e1a72d9f5cd)

**Comment by rsjtdrjgfuzkfg** [comment]
Not sure if 129 is an actual official non-beta release, but to avoid ambiguity: I only support ESR releases of Thunderbird. The add-on might work if you disable compatibility checks, though.

**Comment by Ollipop030** [comment]
> Not sure if 129 is an actual official non-beta release

Yes it is. Mozilla change its release channels to daily, beta, release (which is 129) and esr.
