### ISSUE TITLE
Support for Thunderbird 131

### ISSUE THREAD

**Issue by update-freak** [rsjtdrjgfuzkfg/thunderbird-birthdaycalendar#34]
It would be great if the birthdaycalender would support also the current version of Thunderbird 131.

**Comment by rsjtdrjgfuzkfg** [comment]
Thunderbird 131 is an experimental version; I never supported those but you can try to bump the compatibility yourself - the add-on *might* work without changes.

In a more general sense: in the past, I only supported official releases; once Thunderbird switches to monthly releases I'll change that policy to only support ESR releases.

**Comment by update-freak** [comment]
Ah ok. Did not know that v131 is experimental.
Thank you for the info.
Then I will use the lates ESR release :)
