### ISSUE TITLE
Calculate Age 

### ISSUE THREAD

**Issue by Tuxmorale** [rsjtdrjgfuzkfg/thunderbird-birthdaycalendar#4]
In the age calculation function, 
to see the years you have to divide by 2
for example
see 2 years (2020-2021) you have to set 4 years (4/2 = 2)
see 3 years (2020-2022) you have to set 6 years (6/2 = 3)
Sorry for the bad English

**Comment by rsjtdrjgfuzkfg** [comment]
No, the age is also calculated in the past: 4 years (the default) is currently calculating ages for 2018-2021; 6 years is calculating 2017-2022.

I decided against two separate inputs (years in the past + years in the future) as that seemed unnecessarily complex, but maybe there is room for improvement in how to display the setting...

I'm closing this for now, but feel free to comment if you have a concrete idea on how to make it more obvious how the feature works.
