### ISSUE TITLE
CardBook support

### ISSUE THREAD

**Issue by nekr0z** [rsjtdrjgfuzkfg/thunderbird-birthdaycalendar#7]
I would be really nice if this addon supported [CardBook](https://gitlab.com/CardBook/CardBook) address books.

**Comment by rsjtdrjgfuzkfg** [comment]
If you want to view the birthdays of your CardBook contacts, you should use CardBook's own birthday calendar features: actively working against the developer's intentions seems like a bad idea and could cause issues down  the road. After all, CardBook is more an independent application than an extension for Thunderbird.

Currently, CardBook support is also not feasible from a technical point of view: CardBook is – at least currently – incompatible with any Thunderbird add-on that wants to do anything with the address book.

For both reasons together, I'm closing here. That being said, I'd be open to accept a patch if somebody finds a clean way to access CardBook using only stable interfaces or to support developers wanting to start a CardBook-related fork.

**Comment by nekr0z** [comment]
> CardBook is incompatible with any Thunderbird add-on that wants to do anything with the address book.

I believe Mail Merge is an example of the opposite, but you have more expertise here. Thank you for looking into this.

**Comment by rsjtdrjgfuzkfg** [comment]
I had a look at Mail Merge, they are accessing CardBook's internals directly. That will work as long as CardBook does not change how it internally deals with data, but is not stable (changes in CardBook could break Mail Merge) and requires Mail Merge to basically support two different applications.

I could imagine a fork of this add-on using the same method, but would not want to maintain it.

Imho, the best solution would be for CardBook to add support for the address book APIs of Thunderbird, then all add-ons will work out of the box, without needing any CardBook-specific changes.
