### ISSUE TITLE
Duplicate birthdays when using age calculation

### ISSUE THREAD

**Issue by tinutac** [rsjtdrjgfuzkfg/thunderbird-birthdaycalendar#9]
I've noticed a minor issue. If you select 1 in the age calculation then there's no age calculated (displayed). If I understand correctly this should generate birthday events for one year with the age calculated? 
Related to this... for some contacts, if I set more than 1 year, for some contacts there seem to be 2 events being generated (one with the age, one without the age).

**Comment by rsjtdrjgfuzkfg** [comment]
> If you select 1 in the age calculation then there's no age calculated (displayed).

In my tests, the ages are calculated, but one year too early. I assume it is the same for you, and you just did not check 2020. Thanks for the report!

> for some contacts, if I set more than 1 year, for some contacts there seem to be 2 events being generated (one with the age, one without the age).

Could you provide me with an example contact that triggers this behavior and mention the platform and timezone you're on? I'd guess there is a miscalculation that causes Thunderbird to place the event series at a different time than the add-on expects it, so the exception rules for the event series are off.

**Comment by tinutac** [comment]
I've looked a little bit in the code but my javascript is a little bit rusty :-). I think the problem comes from provider.js. I'm not sure I understand clearly why you add the birthYear to the years array. I've tested with a temporary extension with a minor mod and it seems fine now.
I would modify the line 59 to:
`let years = [];`
And remove the line 61.
I've emailed two contacts, one that triggers the bug and one that doesn't.

**Comment by rsjtdrjgfuzkfg** [comment]
> I've emailed two contacts, one that triggers the bug and one that doesn't.

Did not get that. Did you really send it to the email address listed as "Support E-mail" on https://addons.thunderbird.net/en-us/thunderbird/addon/birthday-calendar/ ?

> I'm not sure I understand clearly why you add the birthYear to the years array.
This is necessary to trigger the generation of the event series starting at the birth year, see https://github.com/rsjtdrjgfuzkfg/thunderbird-birthdaycalendar/blob/master/src/provider.js#L84 for the special handling of that one. Your proposed change just removes birthday events that do not have an age ;)

**Comment by rsjtdrjgfuzkfg** [comment]
Closing here as the main issue is tracked in #10, while I did not receive any further input to reproduce the second issue.
